from tkinter import *
root=Tk()
root.geometry('500x900')
root.resizable(0,0)
root.title('Bill')
root.iconbitmap('./Images/icon.ico')
frame1=Frame(root,height=598,width=498,background="white")
frame1.place(x=1,y=1)
comName=Label(frame1,text='Company name',font=('Times new roman bold',20),background='white')
comName.place(x=150,y=10)
comAddr1=Label(frame1,text='Address Line 1',font=('Times new roman bold',12),background='white')
comAddr1.place(x=180,y=50)
comAddr2=Label(frame1,text='Address Line 2 , Pin-******',font=('Times new roman bold',12),background='white')
comAddr2.place(x=140,y=70)
comPh=Label(frame1,text='Ph. No. :',font=('Times new roman bold',12),background='white')
comPh.place(x=150,y=90)     
comPh=Label(frame1,text='+91**********',font=('Times new roman bold',12),background='white')
comPh.place(x=210,y=90)     
root.mainloop()